spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SpringSecurityDemoApp
    username: postgres
    password: postgres
      
server:
  servlet:
    context-path: /spring-security
    
 